name: authenticate-aws
description: Authenticate AWS

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.16
        registry-url: https://registry.npmjs.org/
    - name: install-npm
      run: npm i -g npm@8.19.3
      shell: bash
    - name: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::662873414964:role/githubCiCdAccess
        aws-region: eu-central-1
