version: "3.4"
services:
  storyteller:
    container_name: storyteller
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - dynamodb
      - postgres
    links:
      - dynamodb
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -inMemory"
    networks:
      - app
  postgres:
    container_name: postgres
    image: postgres:10-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - app
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8088:8088
    networks:
      - app

networks:
  app:
