name: execute-tests
description: Execute tests

runs:
  using: composite
  steps:
    - name: installation
      shell: bash
      run: npm clean-install
    - name: lint-tests
      shell: bash
      run: npm run test-lint 
    - name: type-tests
      shell: bash
      run: npm run test-types 
    - name: code-tests
      shell: bash
      run: npm run test 
