name: authenticate-aws
description: Authenticate AWS

runs:
  using: composite
  steps:
    - name: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: $AWS_ROLE_ARN_GITHUB_CICD
        aws-region: eu-central-1
