name: perform-tests
description: Perform tests

runs:
  using: composite
  steps:
    - name: installation
      shell: bash
      run: npm clean-install
    - name: lint-tests
      shell: bash
      run: npm run test-lint
    - name: type-tests
      shell: bash
      run: npm run test-types
    - name: copy '.env.dist' to '.env'
      shell: bash
      run: cp .env.dist .env
    - name: start storyteller service
      shell: bash
      run: pwd && ls && npm i -g @micro-package/cli && storyteller start --serviceStdio=inherit
    - name: code-tests
      shell: bash
      run: storyteller dispatch-event --eventName=testStartRequested --testNames[0]=typeorm --dockerComposeFilePath="./docker-compose.yml"
