name: deprecate

on:
  workflow_dispatch:
   inputs:
      versionRange:
        description: 'A version to deprecate - https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies'
        required: true
        type: string
      reasonMessage:
        description: "A reason why those versions must be marked as deprecated - e.g. critical bug fixed in v0.2.3\nIf left empty it will un deprecate version"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deprecate-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: deprecate
        run: npm deprecate @${{ github.repository }}@${{ github.event.inputs.versionRange }} "${{ github.event.inputs.reasonMessage }}"
        env:
          NODE_AUTH_TOKEN: ${{ env.MICRO_PACKAGE_GITHUB_ACTIONS_NPM_NODE_AUTH_TOKEN }}
