name: is-package-version-updated

on:
  workflow_dispatch:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "edited"
      - "synchronize"

permissions:
  id-token: write
  contents: read

jobs:
  is-package-version-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install-deps
        run: |
          sudo apt-get install jq --force-yes
          curl https://gist.githubusercontent.com/Ariel-Rodriguez/9e3c2163f4644d7a389759b224bfe7f3/raw/816453441da56058b73af5812db6217fb71897d2/semver.sh >> semver.sh
          chmod +x semver.sh
      - name: set-version-variables
        id: set-version-variables
        run: |
          ONLINE_VERSION=`curl https://registry.npmjs.org/@micro-package/storyteller | jq -r '."dist-tags".latest'`
          LOCAL_VERSION=`cat ./.dist/package.json | jq -r '.version'`
          echo "ONLINE_VERSION=$ONLINE_VERSION" >> $GITHUB_OUTPUT
          echo "LOCAL_VERSION=$LOCAL_VERSION" >> $GITHUB_OUTPUT
      - name: show-version-variables
        run: |
          echo "ONLINE_VERSION=${{ steps.set-version-variables.outputs.ONLINE_VERSION }}"
          echo "LOCAL_VERSION=${{ steps.set-version-variables.outputs.LOCAL_VERSION }}"
          echo "VERSION_VECTOR=`./semver.sh ${{ steps.set-version-variables.outputs.LOCAL_VERSION }} ${{ steps.set-version-variables.outputs.ONLINE_VERSION }}`"
      - name: validate-version-variables
        id: validate-version-variables 
        run: |
          VERSION_VECTOR=`./semver.sh ${{ steps.set-version-variables.outputs.LOCAL_VERSION }} ${{ steps.set-version-variables.outputs.ONLINE_VERSION }}`
          rm ./semver.sh
          if [ $VERSION_VECTOR = 1 ]; 
            then echo "Package version in pull request is greater than one published version - merge to master allowed" && echo "IS_READY=true" >> $GITHUB_OUTPUT; 
            else echo "Package version in pull request cannot update published version - merge to master disallowed" && echo "IS_READY=false" >> $GITHUB_OUTPUT && exit 1; 
          fi
      # - name: bump-version
      #   if: steps.validate-version-variables.outputs.IS_READY == 'false'
      #   run: |
      #     git config --global user.email "lukasz.klejszta@tsh.io"
      #     git config --global user.name "lukasz.klejszta"
      #     git clone git@github.com:micro-package/storyteller.git
      #     cd storyteller
      #     echo "checkout"
      #     git checkout -b ${{ github.head_ref }}
      #     cd .dist
      #     export NEW_VERSION=`npm version patch --no-git-tag-version`
      #     cd ..
      #     npm run pre4pub
      #     echo "add"
      #     git add package.json package-lock.json .dist/package.json .dist/package-lock.json
      #     echo "commit"
      #     git commit --no-verify --message "feat(Waterfall): automatic version bump to $NEW_VERSION"
      #     echo "push"
      #     git push
        
