name: merge-and-publish-new-version

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  merge-and-publish-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          ssh-key: "${{ env.MICRO_PACKAGE_GITHUB_ACTIONS_DEPLOY_KEY_PRIVATE }}"
      - name: check-version
        run: |
          git rev-parse --abbrev-ref HEAD
      # - name: automerge
      #   uses: "pascalgn/automerge-action@v0.15.5"
      #   env:
      #     GITHUB_TOKEN: "${{ env.MICRO_PACKAGE_GITHUB_ACTIONS_DEPLOY_KEY_PRIVATE }}"
      #     MERGE_LABELS: "automerge,!work in progress"
      #     MERGE_REMOVE_LABELS: "automerge"
      #     MERGE_METHOD: "squash"
      #     MERGE_COMMIT_MESSAGE: "pull-request-description"
      #     MERGE_FORKS: "false"
      #     MERGE_RETRIES: "6"
      #     MERGE_RETRY_SLEEP: "10000"
      #     MERGE_REQUIRED_APPROVALS: "0"
      #     UPDATE_LABELS: ""
      #     UPDATE_METHOD: "rebase"
      #     PULL_REQUEST: "1234"
        
