name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16
          registry-url: https://registry.npmjs.org/
      - uses: ./.github/actions/execute-tests
      - name: prepare-for-publication
        run: npm run pre4pub
      - uses: ./.github/actions/authenticate-aws
      - uses: ./.github/actions/get-aws-secrets
      - name: publication
        run: cd .dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ env.MICRO_PACKAGE_GITHUB_ACTIONS_NPM_NODE_AUTH_TOKEN }}
